name: alp_shoes_secondbrand_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.2
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  provider: ^6.1.1
  image_picker: ^1.0.4
  mime: ^1.0.4
  intl: ^0.19.0
  confetti: ^0.7.0
  month_year_picker: ^0.4.0+1
  url_launcher: ^6.3.2
  flutter_animate: ^4.5.0
  onesignal_flutter: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
  - assets/images/logo_apl.png
  - assets/images/computer.png
  - assets/images/trolley.png
  - assets/images/profit-growth.png
  - assets/images/inventory-management.png
  - assets/images/trolley_2.png
  - assets/images/profit-growth_2.png
  - assets/images/manajemen_stok.png
  - assets/images/catat_transaksi.png
  - assets/images/statistik_laba.png